### ISSUE TITLE
康涛 你们的项目是怎么了

### ISSUE THREAD

**Issue by lipeng5211314** [atguigu-Team-four/Project-number-four#1]
为什么出来很多乱码

**Comment by kt18230927783** [comment]
详细解释请参见：https://www.baidu.com/link?url=kG3zU8f625xVDotrOm2HehCPvoUdWxJSq-hAPsa5g3xhTGW7Ly8MJrfBsZDqkROn0GfBJy3VJz3trOPSg2VOGHJKqeXQTqyrEIgfi-r8Wgy2IRQBZPglfQLR4yiMdJ3u&wd=&eqid=e9bedfc6000388b2000000065e3e6368

**Comment by kt18230927783** [comment]
> 为什么出来很多乱码

详细解释请参见：https ://www.baidu.com/link ? url = kG3zU8f625xVDotrOm2HehCPvoUdWxJSq-hAPsa5g3xhTGW7Ly8MJrfBsZDqkROn0GfBJy3VJz3trOPSg2VOGHJKqeXQQR4GeJbQeBQy4Q7ByCeJQeQQB6Y3CeJeQQ2Q6Y1E1E0E0E0E0E0E0E0E0E0B0B0B0B

**Comment by kt18230927783** [comment]
> 为什么出来很多乱码

详细解释请参见：http://play.taihe.com/?__methodName=mboxCtrl.playSong&fm=altg&__argsValue=286087#
